#!/bin/bash

processing-java --sketch=/Users/dsa157/Documents/Processing/projects/CreateNFTs --output=/Users/dsa157/Documents/Processing/projects/out1 --force --run -Dmode=mint -DdataFile=./output/cli-612-metadata.csv -Dnum=1

